name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: uses: actions/upload-artifact@v4

      - name: Configurar Node.js
        uses: uses: actions/upload-artifact@v4
        with:
          node-version: 18

      - name: Configurar Java
        uses: uses: actions/upload-artifact@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Instalar dependências
        run: npm install

      - name: Sincronizar Capacitor
        run: npx cap sync android

      - name: Permissão Gradle
        run: chmod +x android/gradlew

      - name: Gerar APK
        run: cd android && ./gradlew assembleDebug

      - name: Salvar APK
        uses: uses: actions/upload-artifact@v4
        with:
          name: KDC2Recipies
          path: android/app/build/outputs/apk/debug/app-debug.apk